export type Language = "es" | "en" | "it" | "pt" | "fr" | "de";

export const translations = {
  es: {
    nav: { home: "Inicio", catalog: "Catálogo", about: "Nosotros", contact: "Contacto", lang: "🇪🇸 Español" },
    hero: { badge: "Calidad Premium", subtitle: "El Sabor que Conquista.", btn: "Descubrir Colección" },
    products: { title: "Nuestros Productos", btn: "Explora Nuestros Productos", items: ["Jamón Cocido 500gr", "Jamón Cocido 3,8 Kgs", "Jamón Cocido 6 Kgs"], shape1: "cilindro", shape2: "bloque rectangular", shape3: "forma tradicional", desc: "Descubre nuestra selección exclusiva de embutidos, elaborados con los más altos estándares de calidad y pasión artesanal.", viewAll: "Ver todo el catálogo" },
    social: { title: "¡Síguenos en Redes Sociales!", sub: "Descubre recetas, novedades y mucho más." },
    about: { badge: "Años de Calidad", title: "Nosotros", text1: "Somos una empresa familiar con sólida trayectoria en la ", text2: "elaboración de embutidos y productos alimenticios de alta calidad", text3: ". Fundada por el empresario Álvaro Cozzo T., nuestra misión es ofrecer alimentos que destaquen por su ", text4: "sabor auténtico, calidad superior y amplia variedad", text5: ", llevando a cada mesa el verdadero sabor que conquista.", btn: "Saber Más" },
    contact: { badge: "Soporte y Ventas", title: "Atención y Ventas", desc: "Estamos aquí para atender tus pedidos y resolver cualquier inquietud. Comunícate con nuestros asesores para recibir atención personalizada.", emailLabel: "Correo Electrónico", waLabel: "WhatsApp Ventas", mapLabel: "Sede Principal", mapAddress: "Av. Bolívar Oeste N° 314<br/>Carabobo, Venezuela", formTitle: "Envíanos un mensaje", name: "Tu Nombre", namePlaceholder: "Ej: Carlos Pérez", email: "Tu Correo Electrónico", emailPlaceholder: "correo@empresa.com", msg: "Tu Mensaje", msgPlaceholder: "¿En qué podemos ayudarte?", send: "Enviar Mensaje", map: "Visítanos en nuestra sede", successMsg: "¡Mensaje enviado con éxito! Pronto nos pondremos en contacto." },
    footer: { copy: "Derechos de autor © 2026 Montano Antilia. Todos los derechos reservados.", newsletterTitle: "Únete a nuestra familia", newsletterDesc: "Recibe nuestras últimas novedades y promociones exclusivas directamente en tu correo.", emailPlaceholder: "Tu correo electrónico", subscribeBtn: "Suscribirse", quickLinks: "Navegación", contactTitle: "Contacto Directo" },
    catalogPage: { badge: "Colección 2026", title: "Catálogo", subtitle: "de Embutidos", desc: "Descubre nuestra línea completa de embutidos elaborados bajo estrictos estándares de calidad y la tradición familiar que nos caracteriza.", search: "Buscar por nombre...", emptyTitle: "Sin resultados", emptyDesc: "No encontramos productos que coincidan con tu búsqueda.", clearBtn: "Limpiar filtros", all: "Todos" }
  },
  en: {
    nav: { home: "Home", catalog: "Products", about: "About Us", contact: "Contact", lang: "🇺🇸 English" },
    hero: { badge: "Premium Quality", subtitle: "The Flavor that Conquers.", btn: "Discover Collection" },
    products: { title: "Our Products", btn: "Explore Our Products", items: ["Cooked Ham 500g", "Cooked Ham 3.8 Kg", "Cooked Ham 6 Kg"], shape1: "cylinder", shape2: "rectangular block", shape3: "traditional shape", desc: "Discover our exclusive selection of cold cuts, made with the highest quality standards and artisanal passion.", viewAll: "View full catalog" },
    social: { title: "Follow us on Social Media!", sub: "Discover recipes, news and much more." },
    about: { badge: "Years of Quality", title: "About Us", text1: "We are a family business with a solid track record in the ", text2: "production of high quality cold cuts and food products", text3: ". Founded by entrepreneur Álvaro Cozzo T., our mission is to offer foods that stand out for their ", text4: "authentic flavor, superior quality and wide variety", text5: ", bringing to every table the true flavor that conquers.", btn: "Learn More" },
    contact: { badge: "Support & Sales", title: "Sales & Support", desc: "We are here to take your orders and resolve any concerns. Contact our advisors for personalized attention.", emailLabel: "Email Address", waLabel: "WhatsApp Sales", mapLabel: "Headquarters", mapAddress: "314 West Bolivar Ave<br/>Carabobo, Venezuela", formTitle: "Send us a message", name: "Your Name", namePlaceholder: "E.g. John Doe", email: "Your Email", emailPlaceholder: "email@company.com", msg: "Your Message", msgPlaceholder: "How can we help you?", send: "Send Message", map: "Visit our headquarters", successMsg: "Message sent successfully! We will contact you soon." },
    footer: { copy: "Copyright © 2026 Montano Antilia. All rights reserved.", newsletterTitle: "Join our family", newsletterDesc: "Receive our latest news and exclusive promotions directly in your email.", emailPlaceholder: "Your email address", subscribeBtn: "Subscribe", quickLinks: "Navigation", contactTitle: "Direct Contact" },
    catalogPage: { badge: "2026 Collection", title: "Catalog", subtitle: "of Cold Cuts", desc: "Discover our complete line of cold cuts made under strict quality standards and the family tradition that characterizes us.", search: "Search by name...", emptyTitle: "No results", emptyDesc: "We found no products matching your search.", clearBtn: "Clear filters", all: "All" }
  },
  it: {
    nav: { home: "Home", catalog: "Catalogo", about: "Chi Siamo", contact: "Contatti", lang: "🇮🇹 Italiano" },
    hero: { badge: "Qualità Premium", subtitle: "Il Sapore che Conquista.", btn: "Scopri la Collezione" },
    products: { title: "I Nostri Prodotti", btn: "Esplora i Nostri Prodotti", items: ["Prosciutto Cotto 500g", "Prosciutto Cotto 3,8 Kg", "Prosciutto Cotto 6 Kg"], shape1: "cilindro", shape2: "blocco rettangolare", shape3: "forma tradizionale", desc: "Scopri la nostra selezione esclusiva di salumi, realizzati con i più alti standard di qualità e passione artigianale.", viewAll: "Vedi tutto il catalogo" },
    social: { title: "Seguici sui Social Media!", sub: "Scopri ricette, novità e molto altro." },
    about: { badge: "Anni di Qualità", title: "Chi Siamo", text1: "Siamo un'azienda familiare con una solida esperienza nella ", text2: "produzione di salumi e prodotti alimentari di alta qualità", text3: ". Fondata dall'imprenditore Álvaro Cozzo T., la nostra missione è offrire cibi che si distinguono per il loro ", text4: "sapore autentico, qualità superiore e grande varietà", text5: ", portando su ogni tavola il vero sapore che conquista.", btn: "Scopri di Più" },
    contact: { badge: "Supporto e Vendite", title: "Vendite e Assistenza", desc: "Siamo qui per gestire i tuoi ordini e risolvere ogni dubbio. Contatta i nostri consulenti per un'attenzione personalizzata.", emailLabel: "Indirizzo Email", waLabel: "WhatsApp Vendite", mapLabel: "Sede Principale", mapAddress: "Viale Bolívar Ovest N° 314<br/>Carabobo, Venezuela", formTitle: "Inviaci un messaggio", name: "Il Tuo Nome", namePlaceholder: "Es: Mario Rossi", email: "La Tua Email", emailPlaceholder: "email@azienda.com", msg: "Il Tuo Messaggio", msgPlaceholder: "Come possiamo aiutarti?", send: "Invia Messaggio", map: "Vieni a trovarci", successMsg: "Messaggio inviato con successo! Ti contatteremo presto." },
    footer: { copy: "Copyright © 2026 Montano Antilia. Tutti i diritti riservati.", newsletterTitle: "Unisciti alla nostra famiglia", newsletterDesc: "Ricevi le nostre ultime novità e promozioni esclusive direttamente nella tua email.", emailPlaceholder: "Il tuo indirizzo email", subscribeBtn: "Iscriviti", quickLinks: "Navigazione", contactTitle: "Contatto Diretto" },
    catalogPage: { badge: "Collezione 2026", title: "Catalogo", subtitle: "di Salumi", desc: "Scopri la nostra linea completa di salumi realizzati con rigorosi standard di qualità e la tradizione familiare che ci caratterizza.", search: "Cerca per nome...", emptyTitle: "Nessun risultato", emptyDesc: "Non abbiamo trovato prodotti corrispondenti alla tua ricerca.", clearBtn: "Cancella filtri", all: "Tutti" }
  },
  pt: {
    nav: { home: "Início", catalog: "Catálogo", about: "Sobre Nós", contact: "Contato", lang: "🇵🇹 Português" },
    hero: { badge: "Qualidade Premium", subtitle: "O Sabor que Conquista.", btn: "Descobrir Coleção" },
    products: { title: "Nossos Produtos", btn: "Explore Nossos Produtos", items: ["Presunto Cozido 500g", "Presunto Cozido 3,8 Kg", "Presunto Cozido 6 Kg"], shape1: "cilindro", shape2: "bloco retangular", shape3: "forma tradicional", desc: "Descubra nossa seleção exclusiva de embutidos, feitos com os mais altos padrões de qualidade e paixão artesanal.", viewAll: "Ver todo o catálogo" },
    social: { title: "Siga-nos nas Redes Sociais!", sub: "Descubra receitas, novidades e muito mais." },
    about: { badge: "Anos de Qualidade", title: "Sobre Nós", text1: "Somos uma empresa familiar com sólida experiência na ", text2: "produção de embutidos e produtos alimentícios de alta qualidade", text3: ". Fundada pelo empresário Álvaro Cozzo T., nossa missão é oferecer alimentos que se destaquem por seu ", text4: "sabor autêntico, qualidade superior e grande variedade", text5: ", levando a cada mesa o verdadeiro sabor que conquista.", btn: "Saber Mais" },
    contact: { badge: "Suporte e Vendas", title: "Vendas e Atendimento", desc: "Estamos aqui para atender seus pedidos e esclarecer qualquer dúvida. Entre em contato com nossos consultores para um atendimento personalizado.", emailLabel: "Correio Eletrônico", waLabel: "WhatsApp Vendas", mapLabel: "Sede Principal", mapAddress: "Av. Bolívar Oeste N° 314<br/>Carabobo, Venezuela", formTitle: "Envie-nos uma mensagem", name: "Seu Nome", namePlaceholder: "Ex: João Silva", email: "Seu E-mail", emailPlaceholder: "email@empresa.com", msg: "Sua Mensagem", msgPlaceholder: "Como podemos ajudar?", send: "Enviar Mensagem", map: "Visite-nos em nossa sede", successMsg: "Mensagem enviada com sucesso! Entraremos em contato em breve." },
    footer: { copy: "Direitos autorais © 2026 Montano Antilia. Todos os direitos reservados.", newsletterTitle: "Junte-se à nossa família", newsletterDesc: "Receba nossas últimas novidades e promoções exclusivas diretamente no seu e-mail.", emailPlaceholder: "Seu e-mail", subscribeBtn: "Inscrever-se", quickLinks: "Navegação", contactTitle: "Contato Direto" },
    catalogPage: { badge: "Coleção 2026", title: "Catálogo", subtitle: "de Frios", desc: "Descubra nossa linha completa de embutidos elaborados sob rígidos padrões de qualidade e a tradição familiar que nos caracteriza.", search: "Buscar por nome...", emptyTitle: "Sem resultados", emptyDesc: "Não encontramos produtos correspondentes à sua busca.", clearBtn: "Limpar filtros", all: "Todos" }
  },
  fr: {
    nav: { home: "Accueil", catalog: "Catalogue", about: "À Propos", contact: "Contact", lang: "🇫🇷 Français" },
    hero: { badge: "Qualité Premium", subtitle: "La Saveur qui Conquiert.", btn: "Découvrir la Collection" },
    products: { title: "Nos Produits", btn: "Explorez Nos Produits", items: ["Jambon Cuit 500g", "Jambon Cuit 3,8 Kg", "Jambon Cuit 6 Kg"], shape1: "cylindre", shape2: "bloc rectangulaire", shape3: "forme traditionnelle", desc: "Découvrez notre sélection exclusive de charcuteries, préparées avec les plus hauts standards de qualité et une passion artisanale.", viewAll: "Voir tout le catalogue" },
    social: { title: "Suivez-nous sur les Réseaux Sociaux!", sub: "Découvrez des recettes, des nouveautés et bien plus encore." },
    about: { badge: "Années de Qualité", title: "À Propos", text1: "Nous sommes une entreprise familiale avec une solide expérience dans la ", text2: "production de charcuterie et de produits alimentaires de haute qualité", text3: ". Fondée par l'entrepreneur Álvaro Cozzo T., notre mission est d'offrir des aliments qui se distinguent par leur ", text4: "saveur authentique, qualité supérieure et grande variété", text5: ", apportant à chaque table la véritable saveur qui conquiert.", btn: "En Savoir Plus" },
    contact: { badge: "Support et Ventes", title: "Ventes et Assistance", desc: "Nous sommes là pour prendre vos commandes et répondre à vos questions. Contactez nos conseillers pour une attention personnalisée.", emailLabel: "Adresse E-mail", waLabel: "Ventes WhatsApp", mapLabel: "Siège Social", mapAddress: "Av. Bolívar Ouest N° 314<br/>Carabobo, Venezuela", formTitle: "Envoyez-nous un message", name: "Votre Nom", namePlaceholder: "Ex: Jean Dupont", email: "Votre E-mail", emailPlaceholder: "email@entreprise.com", msg: "Votre Message", msgPlaceholder: "Comment pouvons-nous vous aider ?", send: "Envoyer le Message", map: "Visitez notre siège", successMsg: "Message envoyé avec succès ! Nous vous contacterons bientôt." },
    footer: { copy: "Droits d'auteur © 2026 Montano Antilia. Tous droits réservés.", newsletterTitle: "Rejoignez notre famille", newsletterDesc: "Recevez nos dernières nouvelles et promotions exclusives directement dans votre e-mail.", emailPlaceholder: "Votre adresse e-mail", subscribeBtn: "S'abonner", quickLinks: "Navigation", contactTitle: "Contact Direct" },
    catalogPage: { badge: "Collection 2026", title: "Catalogue", subtitle: "de Charcuterie", desc: "Découvrez notre gamme complète de charcuterie élaborée selon des normes de qualité strictes et la tradition familiale qui nous caractérise.", search: "Recherche par nom...", emptyTitle: "Aucun résultat", emptyDesc: "Nous n'avons trouvé aucun produit correspondant à votre recherche.", clearBtn: "Effacer les filtres", all: "Tous" }
  },
  de: {
    nav: { home: "Startseite", catalog: "Katalog", about: "Über uns", contact: "Kontakt", lang: "🇩🇪 Deutsch" },
    hero: { badge: "Premium Qualität", subtitle: "Der Geschmack, der erobert.", btn: "Kollektion entdecken" },
    products: { title: "Unsere Produkte", btn: "Entdecken Sie unsere Produkte", items: ["Kochschinken 500g", "Kochschinken 3,8 Kg", "Kochschinken 6 Kg"], shape1: "Zylinder", shape2: "rechteckiger Block", shape3: "traditionelle Form", desc: "Entdecken Sie unsere exklusive Auswahl an Wurstwaren, die mit höchsten Qualitätsstandards und handwerklicher Leidenschaft hergestellt werden.", viewAll: "Ganzen Katalog ansehen" },
    social: { title: "Folgen Sie uns auf Social Media!", sub: "Entdecken Sie Rezepte, Neuigkeiten und vieles mehr." },
    about: { badge: "Jahre Qualität", title: "Über Uns", text1: "Wir sind ein Familienunternehmen mit langjähriger Erfahrung in der ", text2: "Herstellung von hochwertigen Wurstwaren und Lebensmitteln", text3: ". Gegründet vom Unternehmer Álvaro Cozzo T., ist es unsere Mission, Lebensmittel anzubieten, die sich durch ", text4: "authentischen Geschmack, hervorragende Qualität und große Vielfalt", text5: " auszeichnen und den wahren Geschmack, der erobert, auf jeden Tisch bringen.", btn: "Mehr Erfahren" },
    contact: { badge: "Support & Vertrieb", title: "Vertrieb & Kundendienst", desc: "Wir sind hier, um Ihre Bestellungen entgegenzunehmen und Fragen zu klären. Kontaktieren Sie unsere Berater für eine persönliche Betreuung.", emailLabel: "E-Mail-Adresse", waLabel: "WhatsApp Vertrieb", mapLabel: "Hauptsitz", mapAddress: "Bolívar Westallee N° 314<br/>Carabobo, Venezuela", formTitle: "Senden Sie uns eine Nachricht", name: "Ihr Name", namePlaceholder: "Z.B. Max Mustermann", email: "Ihre E-Mail-Adresse", emailPlaceholder: "email@unternehmen.com", msg: "Ihre Nachricht", msgPlaceholder: "Wie können wir Ihnen helfen?", send: "Nachricht Senden", map: "Besuchen Sie unseren Hauptsitz", successMsg: "Nachricht erfolgreich gesendet! Wir werden uns in Kürze bei Ihnen melden." },
    footer: { copy: "Urheberrecht © 2026 Montano Antilia. Alle Rechte vorbehalten.", newsletterTitle: "Treten Sie unserer Familie bei", newsletterDesc: "Erhalten Sie unsere neuesten Nachrichten und exklusiven Angebote direkt in Ihrer E-Mail.", emailPlaceholder: "Ihre E-Mail-Adresse", subscribeBtn: "Abonnieren", quickLinks: "Navigation", contactTitle: "Direkter Kontakt" },
    catalogPage: { badge: "Kollektion 2026", title: "Katalog", subtitle: "der Wurstwaren", desc: "Entdecken Sie unsere komplette Linie von Wurstwaren, die unter strengsten Qualitätsstandards und der uns auszeichnenden Familientradition hergestellt werden.", search: "Suche nach Name...", emptyTitle: "Keine Ergebnisse", emptyDesc: "Wir haben keine Produkte gefunden, die Ihrer Suche entsprechen.", clearBtn: "Filter löschen", all: "Alle" }
  }
};
