export type Language = "es" | "en" | "it" | "pt" | "fr" | "de";

export const translations = {
  es: {
    nav: { home: "Inicio", catalog: "Catálogo", about: "Nosotros", contact: "Contacto", lang: "🇪🇸 Español" },
    hero: { badge: "Calidad Premium", subtitle: "El Sabor que Conquista.", btn: "Descubrir Colección" },
    products: { title: "Nuestros Productos", btn: "Explora Nuestros Productos", items: ["Jamón Cocido 500gr", "Jamón Cocido 3,8 Kgs", "Jamón Cocido 6 Kgs"], shape1: "cilindro", shape2: "bloque rectangular", shape3: "forma tradicional", desc: "Descubre nuestra selección exclusiva de embutidos, elaborados con los más altos estándares de calidad y pasión artesanal.", viewAll: "Ver todo el catálogo" },
    social: { title: "¡Síguenos en Redes Sociales!", sub: "Descubre recetas, novedades y mucho más." },
    about: { badge: "Años de Calidad", title: "Nosotros", text1: "Somos una empresa familiar con sólida trayectoria en la ", text2: "elaboración de embutidos y productos alimenticios de alta calidad", text3: ". Fundada por el empresario Álvaro Cozzo T., nuestra misión es ofrecer alimentos que destaquen por su ", text4: "sabor auténtico, calidad superior y amplia variedad", text5: ", llevando a cada mesa el verdadero sabor que conquista.", btn: "Saber Más" },
    contact: { badge: "Soporte y Ventas", title: "Atención y Ventas", desc: "Estamos aquí para atender tus pedidos y resolver cualquier inquietud. Comunícate con nuestros asesores para recibir atención personalizada.", emailLabel: "Correo Electrónico", waLabel: "WhatsApp Ventas", mapLabel: "Sede Principal", mapAddress: "Av. Bolívar Oeste N° 314<br/>Carabobo, Venezuela", formTitle: "Envíanos un mensaje", name: "Tu Nombre", namePlaceholder: "Ej: Carlos Pérez", email: "Tu Correo Electrónico", emailPlaceholder: "correo@empresa.com", msg: "Tu Mensaje", msgPlaceholder: "¿En qué podemos ayudarte?", send: "Enviar Mensaje", map: "Visítanos en nuestra sede", successMsg: "¡Mensaje enviado con éxito! Pronto nos pondremos en contacto." },
    footer: { copy: "Derechos de autor © 2026 Montano Antilia. Todos los derechos reservados.", newsletterTitle: "Únete a nuestra familia", newsletterDesc: "Recibe nuestras últimas novedades y promociones exclusivas directamente en tu correo.", emailPlaceholder: "Tu correo electrónico", subscribeBtn: "Suscribirse", quickLinks: "Navegación", contactTitle: "Contacto Directo" },
    catalogPage: { badge: "Colección 2026", title: "Catálogo", subtitle: "de Embutidos", desc: "Descubre nuestra línea completa de embutidos elaborados bajo estrictos estándares de calidad y la tradición familiar que nos caracteriza.", search: "Buscar por nombre...", emptyTitle: "Sin resultados", emptyDesc: "No encontramos productos que coincidan con tu búsqueda.", clearBtn: "Limpiar filtros", all: "Todos" },
    aboutPage: { heroTitle: "Nuestra Historia", heroSubtitle: "Conoce el corazón detrás de Montano Antilia", tag: "Desde 1990", title1: "Calidad, Tradición y ", title2: "Sabor Inigualable", p1: "Productos Alimenticios Montano Antilia C.A., fundada por Álvaro Cozzo T., es una empresa con sólida trayectoria en la elaboración de embutidos de alta calidad. Desde nuestros inicios, hemos mantenido un firme compromiso con la excelencia, la innovación y la tradición familiar, pilares que nos han permitido posicionarnos como referencia en el mercado venezolano.", p2: "Con años de experiencia en la industria alimentaria, nos especializamos en ofrecer embutidos que combinan sabor auténtico, frescura y confianza. Cada producto que elaboramos refleja nuestro esfuerzo por brindar lo mejor a nuestros clientes, satisfaciendo los paladares más exigentes.", p3: "Nuestra planta principal está ubicada en la Zona Industrial San Vicente II, Calle A con Calle G, Galpón D7, Maracay, Estado Aragua. Además, contamos con una sede en la Av. Bolívar Oeste N° 314, Sector La Coromoto, desde donde seguimos creciendo y fortaleciendo nuestro compromiso de alimentar a Venezuela con productos confiables y de sabor inigualable.", val1: "Excelencia garantizada", val2: "Tradición familiar", val3: "Sabor auténtico", val4: "Ingredientes frescos", stat1: "Años de Experiencia", stat2: "Calidad Premium", stat3: "Productos Únicos", stat4: "Sabor Inigualable", missionTitle: "Nuestra Misión", missionDesc: "Ofrecer a las familias venezolanas embutidos y productos alimenticios de la más alta calidad, elaborados bajo estrictos estándares de higiene y frescura, manteniendo intacto el sabor auténtico y tradicional que nos caracteriza desde nuestros inicios.", visionTitle: "Nuestra Visión", visionDesc: "Consolidarnos como la marca líder de charcutería premium en Venezuela, siendo reconocidos por nuestra innovación constante, el compromiso inquebrantable con la excelencia y nuestra capacidad para llevar el sabor que conquista a mercados internacionales.", ctaTitle: "¿Listo para probar la diferencia?", ctaDesc: "Descubre por qué somos el sabor que conquista la mesa venezolana.", ctaBtn: "Ver Catálogo Completo", back: "Volver" }
  },
  en: {
    nav: { home: "Home", catalog: "Products", about: "About Us", contact: "Contact", lang: "🇺🇸 English" },
    hero: { badge: "Premium Quality", subtitle: "The Flavor that Conquers.", btn: "Discover Collection" },
    products: { title: "Our Products", btn: "Explore Our Products", items: ["Cooked Ham 500g", "Cooked Ham 3.8 Kg", "Cooked Ham 6 Kg"], shape1: "cylinder", shape2: "rectangular block", shape3: "traditional shape", desc: "Discover our exclusive selection of cold cuts, made with the highest quality standards and artisanal passion.", viewAll: "View full catalog" },
    social: { title: "Follow us on Social Media!", sub: "Discover recipes, news and much more." },
    about: { badge: "Years of Quality", title: "About Us", text1: "We are a family business with a solid track record in the ", text2: "production of high quality cold cuts and food products", text3: ". Founded by entrepreneur Álvaro Cozzo T., our mission is to offer foods that stand out for their ", text4: "authentic flavor, superior quality and wide variety", text5: ", bringing to every table the true flavor that conquers.", btn: "Learn More" },
    contact: { badge: "Support & Sales", title: "Sales & Support", desc: "We are here to take your orders and resolve any concerns. Contact our advisors for personalized attention.", emailLabel: "Email Address", waLabel: "WhatsApp Sales", mapLabel: "Headquarters", mapAddress: "314 West Bolivar Ave<br/>Carabobo, Venezuela", formTitle: "Send us a message", name: "Your Name", namePlaceholder: "E.g. John Doe", email: "Your Email", emailPlaceholder: "email@company.com", msg: "Your Message", msgPlaceholder: "How can we help you?", send: "Send Message", map: "Visit our headquarters", successMsg: "Message sent successfully! We will contact you soon." },
    footer: { copy: "Copyright © 2026 Montano Antilia. All rights reserved.", newsletterTitle: "Join our family", newsletterDesc: "Receive our latest news and exclusive promotions directly in your email.", emailPlaceholder: "Your email address", subscribeBtn: "Subscribe", quickLinks: "Navigation", contactTitle: "Direct Contact" },
    catalogPage: { badge: "2026 Collection", title: "Catalog", subtitle: "of Cold Cuts", desc: "Discover our complete line of cold cuts made under strict quality standards and the family tradition that characterizes us.", search: "Search by name...", emptyTitle: "No results", emptyDesc: "We found no products matching your search.", clearBtn: "Clear filters", all: "All" },
    aboutPage: { heroTitle: "Our History", heroSubtitle: "Get to know the heart behind Montano Antilia", tag: "Since 1990", title1: "Quality, Tradition and ", title2: "Unmatched Flavor", p1: "Productos Alimenticios Montano Antilia C.A., founded by Álvaro Cozzo T., is a company with a solid track record in the production of high-quality cold cuts. Since our beginnings, we have maintained a firm commitment to excellence, innovation, and family tradition, pillars that have allowed us to position ourselves as a reference in the Venezuelan market.", p2: "With years of experience in the food industry, we specialize in offering cold cuts that combine authentic flavor, freshness, and trust. Every product we make reflects our effort to provide the best to our customers, satisfying the most demanding palates.", p3: "Our main plant is located in the San Vicente II Industrial Zone, Maracay, Aragua State. In addition, we have a headquarters on West Bolívar Ave, La Coromoto, from where we continue to grow and strengthen our commitment to feeding Venezuela with reliable products of unmatched flavor.", val1: "Guaranteed excellence", val2: "Family tradition", val3: "Authentic flavor", val4: "Fresh ingredients", stat1: "Years of Experience", stat2: "Premium Quality", stat3: "Unique Products", stat4: "Unmatched Flavor", missionTitle: "Our Mission", missionDesc: "To offer Venezuelan families cold cuts and food products of the highest quality, prepared under strict standards of hygiene and freshness, keeping intact the authentic and traditional flavor that has characterized us since our beginnings.", visionTitle: "Our Vision", visionDesc: "To consolidate ourselves as the leading premium charcuterie brand in Venezuela, being recognized for our constant innovation, unwavering commitment to excellence and our ability to bring the flavor that conquers to international markets.", ctaTitle: "Ready to taste the difference?", ctaDesc: "Discover why we are the flavor that conquers the Venezuelan table.", ctaBtn: "View Full Catalog", back: "Back" }
  },
  it: {
    nav: { home: "Home", catalog: "Catalogo", about: "Chi Siamo", contact: "Contatti", lang: "🇮🇹 Italiano" },
    hero: { badge: "Qualità Premium", subtitle: "Il Sapore che Conquista.", btn: "Scopri la Collezione" },
    products: { title: "I Nostri Prodotti", btn: "Esplora i Nostri Prodotti", items: ["Prosciutto Cotto 500g", "Prosciutto Cotto 3,8 Kg", "Prosciutto Cotto 6 Kg"], shape1: "cilindro", shape2: "blocco rettangolare", shape3: "forma tradizionale", desc: "Scopri la nostra selezione esclusiva di salumi, realizzati con i più alti standard di qualità e passione artigianale.", viewAll: "Vedi tutto il catalogo" },
    social: { title: "Seguici sui Social Media!", sub: "Scopri ricette, novità e molto altro." },
    about: { badge: "Anni di Qualità", title: "Chi Siamo", text1: "Siamo un'azienda familiare con una solida esperienza nella ", text2: "produzione di salumi e prodotti alimentari di alta qualità", text3: ". Fondata dall'imprenditore Álvaro Cozzo T., la nostra missione è offrire cibi che si distinguono per il loro ", text4: "sapore autentico, qualità superiore e grande varietà", text5: ", portando su ogni tavola il vero sapore che conquista.", btn: "Scopri di Più" },
    contact: { badge: "Supporto e Vendite", title: "Vendite e Assistenza", desc: "Siamo qui per gestire i tuoi ordini e risolvere ogni dubbio. Contatta i nostri consulenti per un'attenzione personalizzata.", emailLabel: "Indirizzo Email", waLabel: "WhatsApp Vendite", mapLabel: "Sede Principale", mapAddress: "Viale Bolívar Ovest N° 314<br/>Carabobo, Venezuela", formTitle: "Inviaci un messaggio", name: "Il Tuo Nome", namePlaceholder: "Es: Mario Rossi", email: "La Tua Email", emailPlaceholder: "email@azienda.com", msg: "Il Tuo Messaggio", msgPlaceholder: "Come possiamo aiutarti?", send: "Invia Messaggio", map: "Vieni a trovarci", successMsg: "Messaggio inviato con successo! Ti contatteremo presto." },
    footer: { copy: "Copyright © 2026 Montano Antilia. Tutti i diritti riservati.", newsletterTitle: "Unisciti alla nostra famiglia", newsletterDesc: "Ricevi le nostre ultime novità e promozioni esclusive direttamente nella tua email.", emailPlaceholder: "Il tuo indirizzo email", subscribeBtn: "Iscriviti", quickLinks: "Navigazione", contactTitle: "Contatto Diretto" },
    catalogPage: { badge: "Collezione 2026", title: "Catalogo", subtitle: "di Salumi", desc: "Scopri la nostra linea completa di salumi realizzati con rigorosi standard di qualità e la tradizione familiare che ci caratterizza.", search: "Cerca per nome...", emptyTitle: "Nessun risultato", emptyDesc: "Non abbiamo trovato prodotti corrispondenti alla tua ricerca.", clearBtn: "Cancella filtri", all: "Tutti" },
    aboutPage: { heroTitle: "La Nostra Storia", heroSubtitle: "Conosci il cuore dietro Montano Antilia", tag: "Dal 1990", title1: "Qualità, Tradizione e ", title2: "Sapore Ineguagliabile", p1: "Productos Alimenticios Montano Antilia C.A., fondata da Álvaro Cozzo T., è un'azienda con una solida esperienza nella produzione di salumi di alta qualità. Fin dai nostri inizi, abbiamo mantenuto un fermo impegno verso l'eccellenza, l'innovazione e la tradizione familiare, pilastri che ci hanno permesso di posizionarci come punto di riferimento nel mercato venezuelano.", p2: "Con anni di esperienza nell'industria alimentare, siamo specializzati nell'offrire salumi che combinano sapore autentico, freschezza e fiducia. Ogni prodotto che realizziamo riflette il nostro impegno nell'offrire il meglio ai nostri clienti, soddisfacendo i palati più esigenti.", p3: "Il nostro stabilimento principale si trova nella Zona Industriale San Vicente II, Maracay, Stato Aragua. Inoltre, abbiamo una sede in Viale Bolívar Ovest, La Coromoto, da dove continuiamo a crescere e rafforzare il nostro impegno nel nutrire il Venezuela con prodotti affidabili e dal sapore ineguagliabile.", val1: "Eccellenza garantita", val2: "Tradizione familiare", val3: "Sapore autentico", val4: "Ingredienti freschi", stat1: "Anni di Esperienza", stat2: "Qualità Premium", stat3: "Prodotti Unici", stat4: "Sapore Ineguagliabile", missionTitle: "La Nostra Missione", missionDesc: "Offrire alle famiglie venezuelane salumi e prodotti alimentari della massima qualità, preparati secondo rigorosi standard di igiene e freschezza, mantenendo intatto il sapore autentico e tradizionale che ci caratterizza fin dai nostri inizi.", visionTitle: "La Nostra Visione", visionDesc: "Consolidarci come marchio leader della salumeria premium in Venezuela, essendo riconosciuti per la nostra costante innovazione, l'impegno incrollabile verso l'eccellenza e la nostra capacità di portare il sapore che conquista sui mercati internazionali.", ctaTitle: "Pronto a gustare la differenza?", ctaDesc: "Scopri perché siamo il sapore che conquista la tavola venezuelana.", ctaBtn: "Vedi il Catalogo Completo", back: "Indietro" }
  },
  pt: {
    nav: { home: "Início", catalog: "Catálogo", about: "Sobre Nós", contact: "Contato", lang: "🇵🇹 Português" },
    hero: { badge: "Qualidade Premium", subtitle: "O Sabor que Conquista.", btn: "Descobrir Coleção" },
    products: { title: "Nossos Produtos", btn: "Explore Nossos Produtos", items: ["Presunto Cozido 500g", "Presunto Cozido 3,8 Kg", "Presunto Cozido 6 Kg"], shape1: "cilindro", shape2: "bloco retangular", shape3: "forma tradicional", desc: "Descubra nossa seleção exclusiva de embutidos, feitos com os mais altos padrões de qualidade e paixão artesanal.", viewAll: "Ver todo o catálogo" },
    social: { title: "Siga-nos nas Redes Sociais!", sub: "Descubra receitas, novidades e muito mais." },
    about: { badge: "Anos de Qualidade", title: "Sobre Nós", text1: "Somos uma empresa familiar com sólida experiência na ", text2: "produção de embutidos e produtos alimentícios de alta qualidade", text3: ". Fundada pelo empresário Álvaro Cozzo T., nossa missão é oferecer alimentos que se destaquem por seu ", text4: "sabor autêntico, qualidade superior e grande variedade", text5: ", levando a cada mesa o verdadeiro sabor que conquista.", btn: "Saber Mais" },
    contact: { badge: "Suporte e Vendas", title: "Vendas e Atendimento", desc: "Estamos aqui para atender seus pedidos e esclarecer qualquer dúvida. Entre em contato com nossos consultores para um atendimento personalizado.", emailLabel: "Correio Eletrônico", waLabel: "WhatsApp Vendas", mapLabel: "Sede Principal", mapAddress: "Av. Bolívar Oeste N° 314<br/>Carabobo, Venezuela", formTitle: "Envie-nos uma mensagem", name: "Seu Nome", namePlaceholder: "Ex: João Silva", email: "Seu E-mail", emailPlaceholder: "email@empresa.com", msg: "Sua Mensagem", msgPlaceholder: "Como podemos ajudar?", send: "Enviar Mensagem", map: "Visite-nos em nossa sede", successMsg: "Mensagem enviada com sucesso! Entraremos em contato em breve." },
    footer: { copy: "Direitos autorais © 2026 Montano Antilia. Todos os direitos reservados.", newsletterTitle: "Junte-se à nossa família", newsletterDesc: "Receba nossas últimas novidades e promoções exclusivas diretamente no seu e-mail.", emailPlaceholder: "Seu e-mail", subscribeBtn: "Inscrever-se", quickLinks: "Navegação", contactTitle: "Contato Direto" },
    catalogPage: { badge: "Coleção 2026", title: "Catálogo", subtitle: "de Frios", desc: "Descubra nossa linha completa de embutidos elaborados sob rígidos padrões de qualidade e a tradição familiar que nos caracteriza.", search: "Buscar por nome...", emptyTitle: "Sem resultados", emptyDesc: "Não encontramos produtos correspondentes à sua busca.", clearBtn: "Limpar filtros", all: "Todos" },
    aboutPage: { heroTitle: "Nossa História", heroSubtitle: "Conheça o coração por trás da Montano Antilia", tag: "Desde 1990", title1: "Qualidade, Tradição e ", title2: "Sabor Inigualável", p1: "A Productos Alimenticios Montano Antilia C.A., fundada por Álvaro Cozzo T., é uma empresa com sólida trajetória na elaboração de embutidos de alta qualidade. Desde o nosso início, mantivemos um firme compromisso com a excelência, inovação e tradição familiar, pilares que nos permitiram nos posicionar como referência no mercado venezuelano.", p2: "Com anos de experiência na indústria alimentícia, somos especializados em oferecer embutidos que combinam sabor autêntico, frescor e confiança. Cada produto que fabricamos reflete nosso esforço em oferecer o melhor aos nossos clientes, satisfazendo os paladares mais exigentes.", p3: "Nossa fábrica principal está localizada na Zona Industrial San Vicente II, Maracay, Estado Aragua. Além disso, temos uma sede na Av. Bolívar Oeste, La Coromoto, de onde continuamos a crescer e a fortalecer o nosso compromisso de alimentar a Venezuela com produtos confiáveis e de sabor inigualável.", val1: "Excelência garantida", val2: "Tradição familiar", val3: "Sabor autêntico", val4: "Ingredientes frescos", stat1: "Anos de Experiência", stat2: "Qualidade Premium", stat3: "Produtos Únicos", stat4: "Sabor Inigualável", missionTitle: "Nossa Missão", missionDesc: "Oferecer às famílias venezuelanas embutidos e produtos alimentícios da mais alta qualidade, preparados sob rígidos padrões de higiene e frescor, mantendo intacto o sabor autêntico e tradicional que nos caracteriza desde o nosso início.", visionTitle: "Nossa Visão", visionDesc: "Consolidar-nos como a marca líder de charcutaria premium na Venezuela, sendo reconhecidos por nossa constante inovação, compromisso inabalável com a excelência e nossa capacidade de levar o sabor que conquista aos mercados internacionais.", ctaTitle: "Pronto para provar a diferença?", ctaDesc: "Descubra porque somos o sabor que conquista a mesa venezuelana.", ctaBtn: "Ver Catálogo Completo", back: "Voltar" }
  },
  fr: {
    nav: { home: "Accueil", catalog: "Catalogue", about: "À Propos", contact: "Contact", lang: "🇫🇷 Français" },
    hero: { badge: "Qualité Premium", subtitle: "La Saveur qui Conquiert.", btn: "Découvrir la Collection" },
    products: { title: "Nos Produits", btn: "Explorez Nos Produits", items: ["Jambon Cuit 500g", "Jambon Cuit 3,8 Kg", "Jambon Cuit 6 Kg"], shape1: "cylindre", shape2: "bloc rectangulaire", shape3: "forme traditionnelle", desc: "Découvrez notre sélection exclusive de charcuteries, préparées avec les plus hauts standards de qualité et une passion artisanale.", viewAll: "Voir tout le catalogue" },
    social: { title: "Suivez-nous sur les Réseaux Sociaux!", sub: "Découvrez des recettes, des nouveautés et bien plus encore." },
    about: { badge: "Années de Qualité", title: "À Propos", text1: "Nous sommes une entreprise familiale avec une solide expérience dans la ", text2: "production de charcuterie et de produits alimentaires de haute qualité", text3: ". Fondée par l'entrepreneur Álvaro Cozzo T., notre mission est d'offrir des aliments qui se distinguent par leur ", text4: "saveur authentique, qualité supérieure et grande variété", text5: ", apportant à chaque table la véritable saveur qui conquiert.", btn: "En Savoir Plus" },
    contact: { badge: "Support et Ventes", title: "Ventes et Assistance", desc: "Nous sommes là pour prendre vos commandes et répondre à vos questions. Contactez nos conseillers pour une attention personnalisée.", emailLabel: "Adresse E-mail", waLabel: "Ventes WhatsApp", mapLabel: "Siège Social", mapAddress: "Av. Bolívar Ouest N° 314<br/>Carabobo, Venezuela", formTitle: "Envoyez-nous un message", name: "Votre Nom", namePlaceholder: "Ex: Jean Dupont", email: "Votre E-mail", emailPlaceholder: "email@entreprise.com", msg: "Votre Message", msgPlaceholder: "Comment pouvons-nous vous aider ?", send: "Envoyer le Message", map: "Visitez notre siège", successMsg: "Message envoyé avec succès ! Nous vous contacterons bientôt." },
    footer: { copy: "Droits d'auteur © 2026 Montano Antilia. Tous droits réservés.", newsletterTitle: "Rejoignez notre famille", newsletterDesc: "Recevez nos dernières nouvelles et promotions exclusives directement dans votre e-mail.", emailPlaceholder: "Votre adresse e-mail", subscribeBtn: "S'abonner", quickLinks: "Navigation", contactTitle: "Contact Direct" },
    catalogPage: { badge: "Collection 2026", title: "Catalogue", subtitle: "de Charcuterie", desc: "Découvrez notre gamme complète de charcuterie élaborée selon des normes de qualité strictes et la tradition familiale qui nous caractérise.", search: "Recherche par nom...", emptyTitle: "Aucun résultat", emptyDesc: "Nous n'avons trouvé aucun produit correspondant à votre recherche.", clearBtn: "Effacer les filtres", all: "Tous" },
    aboutPage: { heroTitle: "Notre Histoire", heroSubtitle: "Découvrez le cœur de Montano Antilia", tag: "Depuis 1990", title1: "Qualité, Tradition et ", title2: "Saveur Inégalée", p1: "Productos Alimenticios Montano Antilia C.A., fondée par Álvaro Cozzo T., est une entreprise avec une solide expérience dans la production de charcuterie de haute qualité. Depuis nos débuts, nous avons maintenu un engagement ferme envers l'excellence, l'innovation et la tradition familiale, des piliers qui nous ont permis de nous positionner comme une référence sur le marché vénézuélien.", p2: "Forts de plusieurs années d'expérience dans l'industrie alimentaire, nous sommes spécialisés dans l'offre de charcuteries alliant saveur authentique, fraîcheur et confiance. Chaque produit que nous fabriquons reflète notre effort pour offrir le meilleur à nos clients, satisfaisant les palais les plus exigeants.", p3: "Notre usine principale est située dans la zone industrielle San Vicente II, Maracay, État d'Aragua. De plus, nous avons un siège social sur l'avenue Bolívar Ouest, La Coromoto, d'où nous continuons à grandir et à renforcer notre engagement à nourrir le Venezuela avec des produits fiables d'une saveur inégalée.", val1: "Excellence garantie", val2: "Tradition familiale", val3: "Saveur authentique", val4: "Ingrédients frais", stat1: "Années d'Expérience", stat2: "Qualité Premium", stat3: "Produits Uniques", stat4: "Saveur Inégalée", missionTitle: "Notre Mission", missionDesc: "Offrir aux familles vénézuéliennes des charcuteries et des produits alimentaires de la plus haute qualité, préparés selon des normes strictes d'hygiène et de fraîcheur, en gardant intacte la saveur authentique et traditionnelle qui nous caractérise depuis nos débuts.", visionTitle: "Notre Vision", visionDesc: "Nous consolider comme la marque leader de charcuterie premium au Venezuela, reconnue pour notre innovation constante, notre engagement indéfectible envers l'excellence et notre capacité à apporter la saveur qui conquiert sur les marchés internationaux.", ctaTitle: "Prêt à goûter la différence ?", ctaDesc: "Découvrez pourquoi nous sommes la saveur qui conquiert la table vénézuélienne.", ctaBtn: "Voir le Catalogue Complet", back: "Retour" }
  },
  de: {
    nav: { home: "Startseite", catalog: "Katalog", about: "Über uns", contact: "Kontakt", lang: "🇩🇪 Deutsch" },
    hero: { badge: "Premium Qualität", subtitle: "Der Geschmack, der erobert.", btn: "Kollektion entdecken" },
    products: { title: "Unsere Produkte", btn: "Entdecken Sie unsere Produkte", items: ["Kochschinken 500g", "Kochschinken 3,8 Kg", "Kochschinken 6 Kg"], shape1: "Zylinder", shape2: "rechteckiger Block", shape3: "traditionelle Form", desc: "Entdecken Sie unsere exklusive Auswahl an Wurstwaren, die mit höchsten Qualitätsstandards und handwerklicher Leidenschaft hergestellt werden.", viewAll: "Ganzen Katalog ansehen" },
    social: { title: "Folgen Sie uns auf Social Media!", sub: "Entdecken Sie Rezepte, Neuigkeiten und vieles mehr." },
    about: { badge: "Jahre Qualität", title: "Über Uns", text1: "Wir sind ein Familienunternehmen mit langjähriger Erfahrung in der ", text2: "Herstellung von hochwertigen Wurstwaren und Lebensmitteln", text3: ". Gegründet vom Unternehmer Álvaro Cozzo T., ist es unsere Mission, Lebensmittel anzubieten, die sich durch ", text4: "authentischen Geschmack, hervorragende Qualität und große Vielfalt", text5: " auszeichnen und den wahren Geschmack, der erobert, auf jeden Tisch bringen.", btn: "Mehr Erfahren" },
    contact: { badge: "Support & Vertrieb", title: "Vertrieb & Kundendienst", desc: "Wir sind hier, um Ihre Bestellungen entgegenzunehmen und Fragen zu klären. Kontaktieren Sie unsere Berater für eine persönliche Betreuung.", emailLabel: "E-Mail-Adresse", waLabel: "WhatsApp Vertrieb", mapLabel: "Hauptsitz", mapAddress: "Bolívar Westallee N° 314<br/>Carabobo, Venezuela", formTitle: "Senden Sie uns eine Nachricht", name: "Ihr Name", namePlaceholder: "Z.B. Max Mustermann", email: "Ihre E-Mail-Adresse", emailPlaceholder: "email@unternehmen.com", msg: "Ihre Nachricht", msgPlaceholder: "Wie können wir Ihnen helfen?", send: "Nachricht Senden", map: "Besuchen Sie unseren Hauptsitz", successMsg: "Nachricht erfolgreich gesendet! Wir werden uns in Kürze bei Ihnen melden." },
    footer: { copy: "Urheberrecht © 2026 Montano Antilia. Alle Rechte vorbehalten.", newsletterTitle: "Treten Sie unserer Familie bei", newsletterDesc: "Erhalten Sie unsere neuesten Nachrichten und exklusiven Angebote direkt in Ihrer E-Mail.", emailPlaceholder: "Ihre E-Mail-Adresse", subscribeBtn: "Abonnieren", quickLinks: "Navigation", contactTitle: "Direkter Kontakt" },
    catalogPage: { badge: "Kollektion 2026", title: "Katalog", subtitle: "der Wurstwaren", desc: "Entdecken Sie unsere komplette Linie von Wurstwaren, die unter strengsten Qualitätsstandards und der uns auszeichnenden Familientradition hergestellt werden.", search: "Suche nach Name...", emptyTitle: "Keine Ergebnisse", emptyDesc: "Wir haben keine Produkte gefunden, die Ihrer Suche entsprechen.", clearBtn: "Filter löschen", all: "Alle" },
    aboutPage: { heroTitle: "Unsere Geschichte", heroSubtitle: "Lernen Sie das Herz hinter Montano Antilia kennen", tag: "Seit 1990", title1: "Qualität, Tradition und ", title2: "Unvergleichlicher Geschmack", p1: "Productos Alimenticios Montano Antilia C.A., gegründet von Álvaro Cozzo T., ist ein Unternehmen mit einer soliden Erfolgsgeschichte in der Herstellung hochwertiger Wurstwaren. Seit unseren Anfängen pflegen wir ein starkes Engagement für Exzellenz, Innovation und Familientradition – Säulen, die es uns ermöglicht haben, uns als Referenz auf dem venezolanischen Markt zu positionieren.", p2: "Mit jahrelanger Erfahrung in der Lebensmittelindustrie sind wir darauf spezialisiert, Wurstwaren anzubieten, die authentischen Geschmack, Frische und Vertrauen vereinen. Jedes von uns hergestellte Produkt spiegelt unser Bestreben wider, unseren Kunden das Beste zu bieten und selbst die anspruchsvollsten Gaumen zufrieden zu stellen.", p3: "Unser Hauptwerk befindet sich im Industriegebiet San Vicente II, Maracay, Bundesstaat Aragua. Darüber hinaus haben wir einen Hauptsitz in der Bolívar Westallee, La Coromoto, von wo aus wir weiter wachsen und unser Engagement stärken, Venezuela mit zuverlässigen Produkten von unvergleichlichem Geschmack zu versorgen.", val1: "Garantierte Exzellenz", val2: "Familientradition", val3: "Authentischer Geschmack", val4: "Frische Zutaten", stat1: "Jahre Erfahrung", stat2: "Premium Qualität", stat3: "Einzigartige Produkte", stat4: "Unvergleichlicher Geschmack", missionTitle: "Unsere Mission", missionDesc: "Den venezolanischen Familien Wurstwaren und Lebensmittel von höchster Qualität anzubieten, die unter strengen Hygiene- und Frischestandards zubereitet werden und den authentischen und traditionellen Geschmack bewahren, der uns seit unseren Anfängen auszeichnet.", visionTitle: "Unsere Vision", visionDesc: "Uns als führende Premium-Charcuterie-Marke in Venezuela zu konsolidieren und für unsere ständige Innovation, unser unerschütterliches Engagement für Exzellenz und unsere Fähigkeit, den Geschmack, der erobert, auf internationale Märkte zu bringen, anerkannt zu werden.", ctaTitle: "Bereit, den Unterschied zu schmecken?", ctaDesc: "Entdecken Sie, warum wir der Geschmack sind, der den venezolanischen Tisch erobert.", ctaBtn: "Gesamten Katalog ansehen", back: "Zurück" }
  }
};
